
Table remitos {
  id int [pk, increment] // Clave primaria
  fecha date
  tipo varchar(255)//ingreso - egreso
}
Table clientes {
  persona_id int [ref:>personas.id]
  cliente_id int [ref:>outputs.codigo]// Clave primaria
}

Table proveedores {
  persona_id int [ref:>personas.id]
  insumo_id int [ref:> insumos.codigo]
}

Table insumos {
  codigo int [pk, increment] // Clave primaria
  descripcion varchar(255)
  tipoMedicion varchar(255)
  precioUnitario decimal(10,2)
  tipo varchar(255)//interno-externo
}


table composicionInsumo{
  id_padre int [ref:> insumos.codigo]
  id_hijo int [ref:> insumos.codigo]
  cantidad_insumo int
}


Table outputs {
  codigo int [pk, increment] // Clave primaria
  descripcion varchar(255)
  tipoMedicion varchar(255)
  precioUnitario decimal(10,2)
}

Table composicion_outputs{
  output_id int [ref:> outputs.codigo]
  insumo_id int [ref: > insumos.codigo]
  cantidad_insumo int
}
Table facturas {
  tipo_numero int [pk]
  total decimal(10,2)
  fecha date
  id_emisor int [ref:> personas.id]
  remito_id int [ref:> remitos.id]

}

Table personas{
  id int [pk]//cuit o cuil
  tipo varchar(255)//cuil o cuit
  nombre varchar(255)//nombre completo
  direccion varchar(255)
  edad int
  fecha varchar(255)
}

Table telefono{
  numero int  [pk]
  persona_id int [ref: > personas.id]
}

Table detalleRemito{
  remito_id int [ref:> remitos.id]
  output_id int [ref:> outputs.codigo]
  insumo_id int [ref:> insumos.codigo]
  cantidad int
}

Table almaceninsumos{
  insumo_id int [ref:> insumos.codigo]
  cantidad int
}

Table almacenOutputs{
  insumo_id int [ref:> outputs.codigo]
  cantidad int
}

Table ordenProduccion{
  id int [pk,not null]
  estado varchar(255)
  descripcion varchar(255)
  output_id int [not null, ref:> outputs.codigo]
  cantidad int
  fecha_inicio date
  fecha_fin date
}

table detalleOrden{
  orden_id int [ref:> ordenProduccion.id]
  insumo_id int [ref:> insumos.codigo]
  detalle varchar(255)
}
